[package]
name = "ddmw-util"
version = "0.1.0"
authors = ["Jan Danielsson <jan.danielsson@qrnch.com>"]
edition = "2018"
license = "0BSD"
keywords = [ "ddmw" ]
repository = "https://github.com/openqrnch/ddmw-util"
description = "Utility functions for DDMW integrations"

[dependencies]
